server:
  port: 8761
  
spring:
  application:
    name: eureka-service
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka
          